name: Yahoo Indices - Daily Top 3

on:
  schedule:
    - cron: "0 8 * * *"  # Run daily at 08:00 UTC (change as needed)
  workflow_dispatch:    # Allow manual run

jobs:
  fetch-top3:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pandas

      - name: Run index fetcher
        run: python main.py

      - name: Upload CSV artifact
        uses: actions/upload-artifact@v4
        with:
          name: top3_indices
          path: top3_indices.csv
