name: Yahoo Indices - Daily Top 3

on:
  schedule:
    - cron: "0 8 * * *"  # 08:00 UTC daily
  workflow_dispatch:

jobs:
  fetch-top3:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pandas

      - name: Run index fetcher
        run: |
          echo "Running main.py ..."
          python main.py || true
          echo "=== Directory after run ==="
          ls -al

      - name: Upload CSV artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: top3_indices
          path: top3_indices.csv
