name: TradingView Top 3 Indices

on:
  schedule:
    - cron: "0 8 * * *"   # Daily 8:00 UTC
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install pandas selenium webdriver-manager

      - name: Run Script
        run: python main.py
